version: "3.7"
services:
  mysql-service:
    restart: always
    image: mysql:5.7
    env_file:
      - .env
    networks:
      - spring-boot-mysql-network
    expose:
      - "3306"
    ports:
      - "6033:3306"

  identity-approver:
    restart: on-failure
    env_file:
      - .env
    image: idetix/backend:develop
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - spring-boot-mysql-network
      - blockchain-network
    depends_on:
      - mysql-service

  ganache-cli:
    env_file:
      - .env
    image: idetix/ganache-cli
    expose:
      - ${GANACHE_PORT}
    ports:
      - ${GANACHE_PORT}:${GANACHE_PORT}
    networks:
      - blockchain-network

  trust-certificates-api:
    image: idetix/trust-certificates-api
    env_file:
      - .env
    expose:
      - ${TRUST_CERTIFICATES_API_PORT}
    ports:
      - ${TRUST_CERTIFICATES_API_PORT}:9191

  #  guest:
  #    build: .
  #    ports:
  #        - '8081:8081'

  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "8080:8080"
      - "4001:4001"
      - "5001:5001"
    volumes:
      - "./ipfs_data:/data/ipfs"
      - "./ipfs_staging:/export"

networks:
  spring-boot-mysql-network:
    driver: bridge
  blockchain-network:
    driver: bridge

volumes:
  ipfs:
