version: "3.7"
services:
  mysql-service:
    restart: always
    image: mysql:5.7
    env_file:
      - ./.env
    networks:
      - spring-boot-mysql-network
    expose:
      - "3306"
    ports:
      - "6033:3306"

  identity-approver:
    restart: on-failure
    env_file:
      - ./.env
    image: idetix/backend:develop
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

    networks:
      - spring-boot-mysql-network
      - blockchain-network
    depends_on:
      - mysql-service

  ganache-cli:
    env_file:
      - ./.env
    image: idetix/ganache-cli
    expose:
      - ${GANACHE_PORT}
    ports:
      - ${GANACHE_PORT}:${GANACHE_PORT}
    command: bash -c "ganache-cli --h 0.0.0.0 --port ${GANACHE_PORT} --db ./ganache-db --mnemonic '${MNEMONIC}'"
    networks:
      - blockchain-network
  
  demo-host-website:
    env_file:
      - ./.env
    image: idetix/demo-host-website
    expose:
      - ${DEMO_HOST_WEBSITEPORT_PORT}
    ports:
      - ${DEMO_HOST_WEBSITEPORT_PORT}:80

networks:
  spring-boot-mysql-network:
    driver: bridge
  blockchain-network:
    driver: bridge
