RUN docker-compose exec ipfs config --json API.HTTPHeaders.Access-Control-Allow-Origin "[\"*"]"
RUN docker-compose exec ipfs config --json API.HTTPHeaders.Access-Control-Allow-Methods "[\"GET\", \"POST\"]"
